### ISSUE TITLE
Installing gives The child node "redis" at path "maba_gentle_force" must be configured.

### ISSUE THREAD

**Issue by mehdibo** [mariusbalcytis/gentle-force-bundle#23]
When I run 

`composer require maba/gentle-force-bundle`

I get:

```
Executing script cache:clear
Executed script cache:clear  [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 216:
!!                                                                            
!!    The child node "redis" at path "maba_gentle_force" must be configured.  
!!                                                                            
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.
```

**Comment by pingou2712** [comment]
I have the same problem...
It's been 12 days !! It's really a shame that there was no response or even that you posted your own solution ...
I give you mine when I find ....

**Comment by mehdibo** [comment]
@pingou2712 Just create the file **config/packages/maba_gentle_force.yaml** manually and paste this in it:

```
maba_gentle_force:
  redis:
    host: '%env(REDIS_HOST)%'
  limits:
    global:
      - max_usages: 100
        period: 5m
  listeners:
    - path: ^/
      limits_key: global
      identifiers: [ip]
    - path: ^/
      limits_key: global
      identifiers: [username]
```
