### ISSUE TITLE
Show recaptcha on every request

### ISSUE THREAD

**Issue by a-frolov-paysera** [mariusbalcytis/gentle-force-bundle#40]
Hi all, thanks for bundle)

I need to create functionality, which will show recaptcha for every request
I made such configuration:
```yaml
        test_limit:
            - max_usages: 0.5   // Yeah, it works to show recaptcha on every request
              period: 1d
      listeners
        - path: ^/api/create
          limits_key: test_limit
          identifiers: [ username, test_limit_identifier ]
          methods: [ POST ]
          strategy: recaptcha_headers
```

But problem, that after filling recaptcha, request is not sent.
Could i make, that after filling recaptcha, request will continue be sent to server ?

Thanks
