### ISSUE TITLE
How can I check bundle is working correctly?

### ISSUE THREAD

**Issue by krajcikondra** [mariusbalcytis/gentle-force-bundle#41]
Hi, this is my configuration

```
# DDOS PROTECTION
maba_gentle_force:
    redis:
        host: '%env(REDIS_HOST)%'
    limits:
        api_request:
            - max_usages: 100 # max usage 100 requests per minute
              period: 1m
              bucketed_period: 1h
    listeners:
        - path: ^/
          limits_key: api_request
          identifiers: [ip]
        - path: ^/
          limits_key: api_request
          identifiers: [username]
```

When I run script in google chrome console

```
# this script send 600 requests per minute 
setInterval(function() {
    fetch('https://myweb.com/api/something');
}, 100);
```

But after one minute of running this script still getting response 200 OK. Is my configuration correct?
