### ISSUE TITLE
Symfony 3.3 : Connection refused [tcp://127.0.0.1:6379] 

### ISSUE THREAD

**Issue by blacxi** [mariusbalcytis/gentle-force-bundle#42]
Hi,
On an old project in Symfony 3.3 (sorry, I can't upgrade), I'm trying to use your bundle to protect the connection against brutforcing.
After adding and configuring a redis container, I got the following error which occurs after connection. do you know what could be the reason please?

I can connect to my redis container and the PING command works well in the REDIS-CLI.

```
Connection refused [tcp://127.0.0.1:6379]
CRITICAL | request	| Uncaught PHP Exception Predis\Connection\ConnectionException: "Connection refused [tcp://127.0.0.1:6379]" at /var/www/.../vendor/predis/predis/src/Connection/AbstractConnection.php line 155
```

Here are my configurations

docker-compose.yml

```
    redis:
        image: redis:6.0
        command: redis-server --port 6379 --maxmemory 64mb --maxmemory-policy volatile-lfu --appendonly yes
        ports:
          - 6379:6379
        networks:
            main:
                aliases:
                    - redis
```

services.yaml
```
services:
    cache.redis:
        public: true
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        parent: cache.adapter.redis
        tags:
            -   name: 'cache.redis'
                clearer: cache.app_clearer
                provider: 'redis://127.0.0.1'
                namespace: 'project_name'
```

config for "maba/gentle-force-bundle": "0.5.4",
```
maba_gentle_force:
    redis:
        host: '127.0.0.1'
        failure_strategy: fail
    limits:
        credentials_error:
            - max_usages: 3
              period: 1m
              bucketed_usages: 2

            - max_usages: 10
              period: 1d
    listeners:
        - path: ^/login         # match only POST requests to /login*
          methods: [POST]
          limits_key: credentials_error
          identifiers: [ip]
          strategy: ~
          success_statuses: ['302']
    strategies: ~
```
![Connection-refused-tcp-127-0-0-1-6379-500-Internal-Server-Error- (1)](https://github.com/mariusbalcytis/gentle-force-bundle/assets/6714592/4fd3d28e-8251-4652-a0c4-412d2732dcea)

Best regards,
Blacxi
