### ISSUE TITLE
Unrecognized option "listener_priorities" under "maba_gentle_force"

### ISSUE THREAD

**Issue by thijskaspers** [mariusbalcytis/gentle-force-bundle#8]
In your full config reference there's an option that states "listener_priorities". Setting that returns the following error:

`Unrecognized option "listener_priorities" under "maba_gentle_force"`

I'm also having a hard time getting your bundle to work. Here is my configuration:

````
maba_gentle_force:
    redis:
        host: '%env(REDIS_HOST)%'
    limits:
        credentials_error:
            - max_usages: 5
              period: 10m
    listeners:
        - path: ^/login
          limits_key: credentials_error
          identifiers: [ip, username]
          methods: [POST]
    listener_priorities:
        default: 1000
````

Somehow the above config isn't working. It won't recognize that the request method is a POST to the login form (without methods: [POST] the standard rate limiting is working) and also, the identifier 'username' isn't working, just IP check is, but we need the combination. So in short, no method and only ip identifier works, but method POST and ip + username isn't.

P.s. We are using the default symfony firewall protection with the 'form_login' option. The basic Symfony authentication utils will handle the login form.
